name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - run: |
          pnpm install
          # pnpm build
          # pnpm test
          # pnpm publint

      - name: Prettier check
        run: pnpm fmt:check

      - name: Type check
        run: pnpm typecheck

      - name: Test
        run: pnpm test
