name: Publish Package to NPM

# Only run on new tags starting with `v`
on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build-publish:
    environment: npm-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm build
      - run: pnpm test

      # Might need --recursive in this publish command?
      - name: Read version and publish
        run: |
          VERSION=$(jq -r .version package.json)
          if [[ "$VERSION" == *alpha* || "$VERSION" == *beta* ]]; then
            pnpm publish --no-git-checks --tag beta
          else
            pnpm publish --no-git-checks
          fi
