name: Publish Package to NPM

# Only run on new tags starting with `v`
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "22.20.0"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - name: Read version and publish
        run: |
          VERSION=$(jq -r .version package.json)
          if [[ "$VERSION" == *alpha* || "$VERSION" == *beta* ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        working-directory: packages/deck.gl-layers
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
